apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-local
  labels:
    app: chat-app-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-app-local
  template:
    metadata:
      labels:
        app: chat-app-local
    spec:
      containers:
        - name: chat-app
          image: taseenjunaid/chat-app:latest
          env:
            - name: PORT
              value: "8000"
            - name: SENDER
              value: Local_user
            - name: RECEIVER
              value: Remote_user
            - name: NATS_URL
              value: "a7d62f596d6eb4e5dbc5e6b87ac63192-1340131761.eu-central-1.elb.amazonaws.com"
          ports:
            - containerPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-local
spec:
  type: NodePort
  selector:
    app: chat-app-local
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000